name: "Hello Action"
description: "Greet someone"
author: "hoge@hoge.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "world"
    
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
